"""Editable dimensions for the Benge backyard concept. All values are millimeters."""
INCH = 25.4
FOOT = 12 * INCH

# Primary deck geometry
UPPER_DECK_WIDTH = 24.5 * FOOT       # 24'-6"
UPPER_DECK_DEPTH = 16 * FOOT
LOWER_DECK_WIDTH = 15 * FOOT
LOWER_DECK_DEPTH = 19 * FOOT

LOWER_DECK_ELEVATION = 32 * INCH
UPPER_DECK_ELEVATION = LOWER_DECK_ELEVATION + 28 * INCH
DECK_THICKNESS = 6 * INCH

# Roof
ROOF_HEIGHT_ABOVE_UPPER = 9 * FOOT
ROOF_THICKNESS = 8 * INCH
ROOF_OVERHANG = 12 * INCH

# Stair concept
STAIR_WIDTH = 4 * FOOT
TREAD_DEPTH = 11 * INCH
MAX_RISER = 7.5 * INCH
LANDING_DEPTH = 5 * FOOT

# Pool and patio
POOL_LENGTH = 34 * FOOT
POOL_WIDTH = 12 * FOOT
POOL_DEPTH_VISUAL = 5 * FOOT
PATIO_BORDER = 4 * FOOT
DECK_TO_POOL_CLEARANCE = 6 * FOOT

# Hot tub visual placeholder
HOT_TUB_WIDTH = 8 * FOOT
HOT_TUB_DEPTH = 8 * FOOT
HOT_TUB_ABOVE_DECK = 1 * FOOT

# Fireplace on far left, flush with upper deck front edge
FIREPLACE_WIDTH = 2 * FOOT
FIREPLACE_DEPTH = 6 * FOOT
FIREPLACE_HEIGHT = UPPER_DECK_ELEVATION + 9 * FOOT

# House placeholder wall (thin wall spanning length of top deck)
HOUSE_DEPTH = 1 * INCH
HOUSE_HEIGHT = UPPER_DECK_ELEVATION + ROOF_HEIGHT_ABOVE_UPPER
HOUSE_WIDTH = UPPER_DECK_WIDTH
DOOR_WIDTH = 6 * FOOT

# Appearance
HOUSE_COLOR = (0.35, 0.43, 0.50)  # blue-gray
DECK_COLOR = (0.45, 0.27, 0.12)
RAILING_COLOR = (0.10, 0.10, 0.10)
BRICK_COLOR = (0.55, 0.18, 0.10)
WATER_COLOR = (0.05, 0.30, 0.65)
PAVER_COLOR = (0.70, 0.70, 0.68)
